image: smartsix/mos-ci

stages:
  - test
  - build

job_test:
  stage: test
  script:
    - cmake .
    - make
    - ./test/s6test
  only:
    - develop
    - master
  tags:
    - docker


job_build:
  stage: build
  script:
    - export FW_VERSION=`cat src/consts.h |grep FIRMWARE_APP_VERSION| awk '{ print $3 }'| sed 's/"//g'`
    - mos build --platform=esp32
    - cp build/fw.zip build/fw_$FW_VERSION.zip
  only:
    - master
  artifacts:
    paths:
    - build/*.zip

  tags:
    - docker

