image: smartsix/mos-ci

stages:
  - test
  - build

variables:
  GITHUB_USERNAME: SECURE
  GITHUB_PASSWORD: SECURE

job_test:
  stage: test
  script:
    - cmake .
    - make
    - ./test/s6test -s
  only:
    - develop
    - master
  tags:
    - docker


job_build:
  stage: build
  script:
    - export FW_VERSION=`cat src/consts.h |grep FIRMWARE_APP_VERSION| awk '{ print $3 }'| sed 's/"//g'`
    - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/cesanta/mos-libs.git
    - mos build --local --verbose --no-libs-update --libs-dir ./mos-libs/  --platform esp32
    - cp build/fw.zip build/fw_$FW_VERSION.zip
  only:
    - master
  artifacts:
    paths:
    - build/*.zip

  tags:
    - docker

